fix: retry on empty logs

diff --git a/.github/workflows/forward-logs.yml b/.github/workflows/forward-logs.yml
--- a/.github/workflows/forward-logs.yml
+++ b/.github/workflows/forward-logs.yml
@@ -28,17 +28,35 @@ jobs:
       - name: Download workflow logs
         run: |
           mkdir logs
-          # Get the job ID of the last job in the workflow run
           LAST_JOB_ID=$(curl -s -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
                         "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${{ github.run_id }}/jobs" | jq -r '.jobs[-2].id')
           echo "LAST_JOB_ID: $LAST_JOB_ID"
 
           LOG_URL="https://api.github.com/repos/${{ github.repository }}/actions/jobs/$LAST_JOB_ID/logs"
           echo "LOG_URL: $LOG_URL"
-          curl -s -o /tmp/logs.txt -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" $LOG_URL
 
-          LOG_SIZE=$(stat -c '%s' /tmp/logs.txt)
-          echo "LOG_SIZE: $LOG_SIZE"
+          retry_count=0
+          max_retries=5
+
+          while [ $retry_count -lt $max_retries ]; do
+            curl -s -o /tmp/logs.txt -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" $LOG_URL
+            LOG_SIZE=$(stat -c '%s' /tmp/logs.txt)
+            echo "LOG_SIZE: $LOG_SIZE"
+
+            if [ "$LOG_SIZE" -eq 0 ]; then
+              echo "Log size is 0. Retrying..."
+              sleep 30
+              retry_count=$((retry_count + 1))
+            else
+              echo "Log size is $LOG_SIZE. Exiting."
+              break
+            fi
+          done
+
+          if [ $retry_count -eq $max_retries ]; then
+            echo "Max retries reached. Failing the step."
+            exit 1
+          fi
 
       - name: Create structured logs
         run: |
